import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MyBar } from '@/components/MyBar'
import { MyLink } from '@/components/MyLink'
import { MyBreadcrumbs } from "@/components/MyBreadcrumbs";
import { MyDrawer } from "@/components/MyDrawer";
import { MySpeedDial } from "@/components/MySpeedDial";
import { MyBottomNavigation } from "@/components/MyBottomNavigation"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <MyBar />
        {/* <MyLink /> */}
        {/* <MyLink /> */}
        {/* <MyBreadcrumbs />
            <MyDrawer />
            <MySpeedDial /> */}
        {children}
        <MyBottomNavigation />
      </body>
    </html>
  )
}
